id: I84434267
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T16:34:10+00:00'
last_modified: '2022-06-07T16:48:45.269163+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD19889
  title: 'མ་ཡི་དྲིན་ལན་བཤགས་མདོ། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9B42:
      image_group_id: I2PD20535
      title: ''
      total_pages: 18
      order: 1
      base_file: 9B42.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
