id: I84434267
legacy_id: P002989
ocr_import_info:
  bdrc_scan_id: W2PD19889
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T16:34:01'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T11:03:02.169823+00:00'
last_modified: 2022-09-03 19:03:06.894832
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2PD19889
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2PD19889
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མ་ཡི་དྲིན་ལན་བཤགས་མདོ།
  author: མཁན་ཆེན་ཁྲ་འགུ་རིན་པོ་ཆེ།
statistics:
  ocr_word_mean_confidence_index: 0.9414728755422209
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I2PD20535:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD20535
      total_pages: 18
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD20535.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9414728755422209
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
