id: P002989
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:32:53.426306
source_metadata:
  id: bdr:W2PD19889
  title: 'མ་ཡི་དྲིན་ལན་བཤགས་མདོ། '
  author: ''
  volumes:
    ed7d0e5a2a7d43f4aa926ab4b929dbdd:
      image_group_id: I2PD20535
      title: ''
      volume_number: 1
      total_pages: 18
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
